[project]
name = "cursor-linkup-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5,<7.0",
    "linkup-sdk>=0.2.4,<0.3",
    "llama-index>=0.12.25,<0.13",
    "llama-index-embeddings-huggingface>=0.5.2,<0.6",
    "llama-index-llms-ollama>=0.5.3,<0.6",
    "mcp[cli]>=1.5.0,<2.0",
    "python-dotenv>=1.0.0,<2.0",
    "nest-asyncio>=1.6.0,<2.0",
    "flask>=3.0.0,<4.0",
]

